### ISSUE TITLE
iOS should check if device canSendText

### ISSUE THREAD

**Issue by kmcgill88** [AppleEducate/flutter_sms#3]
Hi great work!

I noticed you are presenting the `MFMessageComposeViewController` without checking `MFMessageComposeViewController.canSendText()` [here](https://github.com/AppleEducate/flutter_sms/blob/master/ios/Classes/SwiftFlutterSmsPlugin.swift#L22). 

Apple says 
`
Always call this method before attempting to present the message compose view controller. A device may be unable to send messages if it does not support messaging or if it is not currently configured to send messages. This method applies only to the ability to send text messages via iMessage, SMS, and MMS.
`

If you are open to PR's I'd be happy to contribute.

**Comment by AppleEducate** [comment]
Please make a PR i would love to check it out!
