### ISSUE TITLE
iOS sendSMS's result message is incorrect

### ISSUE THREAD

**Issue by kmcgill88** [AppleEducate/flutter_sms#4]
[This line](https://github.com/AppleEducate/flutter_sms/blob/master/ios/Classes/SwiftFlutterSmsPlugin.swift#L27) is called immediately,...before a `sent`,  `canceled` or `failed` is returned by iOS.

I believe you want to move the `result` callback to send back the actual result provided by `MessageComposeResult`.

If you are open to PR's I'd be happy to contribute.

**Comment by AppleEducate** [comment]
I am absolutely open to PR's!
