### ISSUE TITLE
sendSMS change result to enum instead of string

### ISSUE THREAD

**Issue by kmcgill88** [AppleEducate/flutter_sms#8]
I noticed you return a `Future<String>` from [sendSMS](https://github.com/AppleEducate/flutter_sms/blob/master/lib/flutter_sms.dart#L14). What do you think about changing  to `Future<SendResult>`. 
```
String _result = await FlutterSms.sendSMS(message: "yo dawg", recipients: ["1234567890"]);
print("Result is: $_result");
if (_result == "not clear what the result options are") {
// stuff
}
```
to
```
SendResult _result = await FlutterSms.sendSMS(message: "yo dawg", recipients: ["1234567890"]);
print("Result is: $_result");
if (_result == SendResult.success) {
// stuff
}
```

Doing something like ` SendResult.success` would allow pushing the string comparison down into your library and consumers have an easier interface with the enums to determine the result. I'd be happy to implement this if you agree.

**Comment by kmcgill88** [comment]
Have you had enough time to review this idea?

**Comment by AppleEducate** [comment]
Yes I would definitely be open to that. Please feel free to do a pull request. I will also look and see if I can update the implementation. Thank you!

**Comment by AppleEducate** [comment]
Fixed with the PR and: `flutter_sms: 0.0.4`

**Comment by hinterlandsupplyco** [comment]
@rodydavis Was this actually done? It looks like `sendSMS` is still returning a string?

**Comment by rodydavis** [comment]
I am still testing but the latest on GitHub returns a string.

Once I fix the bugs I’ll publish the new version. 

Works on iOS and web for me really well
