### ISSUE TITLE
'flutter_sms/flutter_sms-Swift.h' file not found(IOS)

### ISSUE THREAD

**Issue by immatt2015** [AppleEducate/flutter_sms#9]
I imported this package in my flutter project. But when I try to build my app its throw this error: ``'flutter_sms/flutter_sms-Swift.h' file not found.``.   The version of this plugin is  0.0.4. Thanks

**Comment by immatt2015** [comment]
osx Version: 10.13.6
xcode Version 10.1 (10B61)

**Comment by mschmutter** [comment]
@immatt2015 How did you resolve this issue?
